### PR TITLE
Added compilerOptions

### PR DESCRIPTION
**Pull request by chrome**
This option will allow us to pass some options to compliers.

For example:

``` coffee-script
snockets = new Snockets(compilerOptions: {bare: true})
```

This will resolve issue #20

### CODE REVIEW

**Comment by chrome** [comment]
I'm sorry. I've realized that there can be used multiple compilers at once. 
Now example looks like this:

``` coffee-script
snockets = new Snockets(compilersOptions: {coffee: {bare: true}})
```

**Comment by TrevorBurnham** [comment]
I feel like users who want to do this should override `compilers.coffee` themselves. It's a fairly niche use case, and replacing `compilers.coffee` gives you a lot more flexibility (e.g. you could make some things bare and some not, depending on the filename or a directive in the file).

**Comment by chrome** [comment]
Then you should write a few lines about this in readme, because this is not really obviously :)

**Comment by zfogg** [comment]
@TrevorBurnham how exactly would one do that? I kind of need to require some files with --bare and some without.

**Comment by zyll** [comment]
@zachfogg oveririding require('snockets').compilers.coffee.compileSync or adding an other file ext  require('snockets').compilers.bare = {....}

**Comment by pthrasher** [comment]
Hey guys,

I've taken over maintenance on this project, and I'm considering some kind of implementation of what's requested here for the 2.0 release at the end of the month.

@zachfogg what's an example case where you would need some bare and some not?

**Comment by zfogg** [comment]
I've forgotten my need for that by now, unfortunately, but I'm sure there are some uses for that feature.

**Comment by jwalton** [comment]
I could use a feature like this.  I have a whole pile of UI widgets in a folder, and right now we combine them into one giant js file with a "require_tree":

```
#=require ./common
#=require_tree ./widgets

buildWidget = (widgetName) ->
    ...
```

The problem is, in order for `buildWidget` to reference a widget, the widget has to be defined in a global variable, which is kind of annoying.  So in "common" I define `window.benbria.widgets = {}`, and then all my widgets defined themselves on that object.

Ideally, I could do something like:

```
widgets = {}

#= require_tree_bare ./widgets

buildWidget = (widgetName) ->
    return new widgets[widgetName]()
```

then `widgets` is a local variable, and doesn't pollute the global namespace.

**Pull request closed without merging**
