### PR TITLE
Added an option to allow users to turn mangling off

### PR DESCRIPTION
**Pull request by Fresheyeball**
```
    @options.mangle ?= true 
```

---

```
  if flags.minify
    if @concatCache[filePath]?.minifiedData
      result = @concatCache[filePath].minifiedData.toString 'utf8'
      concatenationChanged = false
    else
      result = minify concatenation, @options.mangle #argument passed to util for uglify
      @concatCache[filePath].minifiedData = new Buffer(result)
```

---

```
  minify = (js, mangle) ->
      jsp = uglify.parser
      pro = uglify.uglify
      ast = jsp.parse js
      ast = pro.ast_mangle ast if mangle #only mangle if option is true (default to true)
      ast = pro.ast_squeeze ast
      pro.gen_code ast
```

### CODE REVIEW

**Comment by Fresheyeball** [comment]
Accept my pull request! I need this to complete my master plan of angular.js with snockets!

**Comment by ehg** [comment]
I'd like this too.

**Comment by pthrasher** [comment]
Hey guys, I've just taken over maintenance on this repo. I've updated uglifyjs support to 2.0, and I think this is a good feature addition. I'm working on the next release (still quite a few bugs to fix) but the next release is also going to have source map support all the way to the concatenated file. This currently mostly works bug free, and the mangling in my code is currently off by default for the time being (I will turn this back on and make it an option when I release to NPM)... but in the mean time, feel free to pull the code from HEAD.

**Comment by Fresheyeball** [comment]
I'm sorry, I don't understand. If I pull from head I will get the option of mangling? Or mangling off by default?

**Comment by pthrasher** [comment]
@Fresheyeball Right now it's off by default. I'm going to be pushing a number of changes over the next week. Stay tuned.

**Comment by pthrasher** [comment]
I've opened #43 for tracking my progress on 2.0.0. I plan to be done by the end of the month (may).

I'm closing this issue, and the 2.0.0 update will have this feature.

**Comment by Fresheyeball** [comment]
@pthrasher rock on.

**Pull request closed without merging**
