### PR TITLE
Add livescript support

### PR DESCRIPTION
**Pull request by mizchi**
I needed this fature so added them,  but It's up to you.

### CODE REVIEW

**Comment by mizchi** [comment]
sorry, i forgot cake build

**Comment by beppu** [comment]
I would like this feature, too.  Thanks!

**Comment by pthrasher** [comment]
Hey guys, I've taken over maintaining this project, and I plan on adding support for other languages. I'm not sure the best way to approach this problem, whether it's a plugin arch, or included in the main repo is yet to be determined. This is very interesting though.

I'm curious. This PR is about 10 mos old at this point. Is this still a feature you'd use? Or have you moved on to another tool?

**Comment by brodin** [comment]
Can this topic be revisited?

**Comment by pthrasher** [comment]
@brodin How do you mean? I'm currently just getting back into working on snockets after a long hiatus... As I said in my previous comment, I plan on adding support for other languages. My intention is to break the build process up into a pipeline of steps. This way, language support can be done via plugins. All languages should be a separate plugin for the project. I think this is the best course of action for this project, as it allows for the best extensibility going forward. As soon as I have a blueprint for adding language support, I'll look into live-script support and see what kind of effort is involved with creating such a plugin.

**Pull request closed without merging**
