### PR TITLE
Allow array of sources

### PR DESCRIPTION
**Pull request by toots**
When bundling together various JS files, such as vendored sources, app sources, etc.. it is convenient and cleaner to have them in seperate directories, such as `app/js`, `vendor/js`...

This PR is an intent to implement that in Snockets.

### CODE REVIEW

**Comment by vjpr** [comment]
I've implemented this feature here with tests: https://github.com/vjpr/snockets/commit/14e342c46a5e1b321d0e0d7fa6d642b49213d306. I'm going to try it out in production before making a PR.

**Comment by toots** [comment]
Cool, thanks!

**Comment by pthrasher** [comment]
I'm planning on adding this functionality in for the next release.

**Comment by pthrasher** [comment]
Fixed in #43

**Pull request closed without merging**
