### PR TITLE
Fixes #8

### LINKED ISSUE #8: Windows support for require and cake
Require statements for files in subfolders do not work on Windows. This is because the file is requested as folder/file.js, but cached as folder\file.js. Since it is supported to access files using forward slash instead of backslash as directory separator, I suggest just replacing all backslashes with forward slashes.

Also, on Windows the Cakefile tasks needs to spawn "coffee" and "docco" with a .cmd suffix for them to run.

### PR DESCRIPTION
**Pull request by litek**

### CODE REVIEW

**Comment by litek** [comment]
Sorry about the duplicate issues. I'm a bit new to actually using Github.

**Comment by stefankutko** [comment]
+1 for getting this integrated..

**Comment by TrevorBurnham** [comment]
I'd like to minimize special-casing...

```
arguments[0] += '.cmd' if process.platform is 'win32'"
```

Is `coffee` always installed as `coffee.cmd` under Windows? I was unaware of this.

```
filePath.replace /\\/g, '/'
```

Do any other Node apps do this? Why would filePath contain a `\` in the first place?

**Comment by stefankutko** [comment]
"Is coffee always installed as coffee.cmd under Windows? I was unaware of this." -- Yes appears to be the case

"filePath.replace /\/g, '/'" -- I was up late debugging last night.. it has something to do with "path.join.apply" using the OS default.  Not sure though

Thanks for pulling!

**Comment by stefankutko** [comment]
Trevor, would it be possible to cut a new version of snockets with this change and update the dependency in connect-assets?

**Pull request merged**
